import type { Course } from '../types/course'

export const featuredCourses: Course[] = [
  {
    id: 'fm-101',
    title: 'FM Foundations for Working Professionals',
    description: 'Build a strong base in core FM operations and daily service delivery.',
    category: 'Facilities Management',
    durationHours: 2,
    originalPriceInr: 999,
    priceInr: 499,
    level: 'Beginner',
    image: '/course-images/available-1.jpg',
    promoBadge: 'Top seller',
    instructor: 'Priya Nair, CFM',
    rating: 4.7,
    ratingCount: 4120,
  },
  {
    id: 'cre-201',
    title: 'Corporate Real Estate Strategy Essentials',
    description: 'Understand portfolio planning and practical workplace strategy decisions.',
    category: 'Corporate Real Estate',
    durationHours: 3,
    originalPriceInr: 1799,
    priceInr: 999,
    level: 'Intermediate',
    image: '/course-images/available-2.jpg',
    promoBadge: 'Premium',
    instructor: 'Daniel Okonkwo',
    rating: 4.8,
    ratingCount: 2890,
  },
  {
    id: 'mep-150',
    title: 'MEP Systems and Asset Lifecycle Basics',
    description: 'Learn key MEP concepts for maintenance planning and asset health tracking.',
    category: 'Engineering',
    durationHours: 2,
    originalPriceInr: 1299,
    priceInr: 699,
    level: 'Beginner',
    image: '/course-images/available-3.jpg',
    promoBadge: 'Best',
    instructor: 'Marcus Lee, PE',
    rating: 4.6,
    ratingCount: 1534,
  },
  {
    id: 'fm-220',
    title: 'Workplace Safety and Compliance Checklist',
    description: 'Apply safety standards and compliance checks across real FM scenarios.',
    category: 'Facilities Management',
    durationHours: 2,
    originalPriceInr: 1499,
    priceInr: 799,
    level: 'Intermediate',
    image: '/course-images/available-1.jpg',
    promoBadge: 'Bestseller',
    instructor: 'Elena Vasquez',
    rating: 4.5,
    ratingCount: 921,
  },
  {
    id: 'cre-310',
    title: 'Lease Administration and Portfolio Tracking',
    description: 'Manage lease data, timelines, and occupancy metrics with confidence.',
    category: 'Corporate Real Estate',
    durationHours: 3,
    originalPriceInr: 2199,
    priceInr: 1199,
    level: 'Advanced',
    image: '/course-images/available-2.jpg',
    promoBadge: 'Premium',
    instructor: 'James Okafor',
    rating: 4.9,
    ratingCount: 756,
  },
  {
    id: 'ops-180',
    title: 'Helpdesk Operations and Ticket Prioritization',
    description: 'Run support desks efficiently with smart triage and response workflows.',
    category: 'Operations',
    durationHours: 1.5,
    originalPriceInr: 1099,
    priceInr: 599,
    level: 'Beginner',
    image: '/course-images/available-3.jpg',
    promoBadge: 'Top seller',
    instructor: 'Samira Okonkwo',
    rating: 4.4,
    ratingCount: 3402,
  },
]
